language: python
python:
  - "3.6"
os:
  - linux
before_install:
# nothing to be done here
install:
  - pip install --upgrade pip
  - pip install cython
  - pip install codecov
  - python setup.py install

script:
  - nosetests -sv --with-coverage --cover-package=hpbandster

after_success:
  - codecov
